version: "3.4"
services:
  authservice:
    command:
    - authservice
    - run
    - --defaults=dev
    deploy:
      replicas: 1
    environment:
      STORJUP_ROLE: authservice
      STORJ_ALLOWED_SATELLITES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777,12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@localhost:7777
      STORJ_AUTH_TOKEN: super-secret
      STORJ_DEBUG_ADDR: localhost:11111
      STORJ_ENDPOINT: http://localhost:9999
      STORJ_KV_BACKEND: badger://
      STORJ_LISTEN_ADDR: 0.0.0.0:8888
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ROLE: authservice
    image: img.dev.storj.io/storjup/edge:1.58.1
    ports:
    - mode: ingress
      target: 8888
      published: 8888
      protocol: tcp
  cockroach:
    command:
    - start-single-node
    - --insecure
    - --http-addr=localhost:8086
    - --store="/tmp/cockroach"
    deploy:
      replicas: 1
    image: cockroachdb/cockroach
    ports:
    - mode: ingress
      target: 26257
      published: 26257
  gateway-mt:
    command:
    - gateway-mt
    - run
    - --defaults=dev
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJ_AUTH_BASE_URL: http://authservice:8888
      STORJ_AUTH_TOKEN: super-secret
      STORJ_AUTH_URL: http://authservice:8888
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_SERVER_ADDRESS: 0.0.0.0:9999
    image: img.dev.storj.io/storjup/edge:1.58.1
    ports:
    - mode: ingress
      target: 9999
      published: 9999
      protocol: tcp
  linksharing:
    command:
    - linksharing
    - run
    - --defaults=dev
    deploy:
      replicas: 1
    environment:
      STORJ_ADDRESS: 0.0.0.0:9090
      STORJ_AUTH_SERVICE_BASE_URL: http://authservice:8888
      STORJ_AUTH_SERVICE_TOKEN: super-secret
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_PUBLIC_URL: http://localhost:8888
      STORJ_STATIC_SOURCES_PATH: /var/lib/storj/pkg/linksharing/web/static
      STORJ_TEMPLATES: /var/lib/storj/pkg/linksharing/web/
    image: img.dev.storj.io/storjup/edge:1.58.1
    ports:
    - mode: ingress
      target: 9090
      published: 9090
      protocol: tcp
  redis:
    command:
    - redis-server
    deploy:
      replicas: 1
    image: redis:6.0.9
  satellite-api:
    command:
    - satellite
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/satellite-api/
    deploy:
      replicas: 1
    environment:
      STORJUP_ROLE: satellite-api
      STORJ_ADDRESS: 0.0.0.0:7777
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:10000
      STORJ_CONSOLE_AUTH_TOKEN_SECRET: my-suppa-secret-key
      STORJ_CONSOLE_EXTERNAL_ADDRESS: http://localhost:10000/
      STORJ_CONSOLE_GATEWAY_CREDENTIALS_REQUEST_URL: http://localhost:8888
      STORJ_CONSOLE_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_OPEN_REGISTRATION_ENABLED: "true"
      STORJ_CONSOLE_RATE_LIMIT_BURST: "10000"
      STORJ_CONTACT_EXTERNAL_ADDRESS: satellite-api:7777
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/satellite-api/
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=0
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <storj-up@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METAINFO_RATE_LIMITER_ENABLED: "false"
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_ROLE: satellite-api
      STORJ_SERVER_ADDRESS: 0.0.0.0:7777
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:5559
      STORJ_SERVER_REVOCATION_DBURL: redis://redis:6379?db=1
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_USE_PREDEFINED_IDENTITY: "1"
      STORJ_WAIT_FOR_DB: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 7777
      published: 7777
      protocol: tcp
    - mode: ingress
      target: 10000
      published: 10000
      protocol: tcp
  storagenode1:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30000
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode1:30001
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30001
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30002
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30000
      published: 30000
      protocol: tcp
  storagenode10:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30090
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode10:30091
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30091
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30092
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30090
      published: 30090
      protocol: tcp
  storagenode2:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30010
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode2:30011
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30011
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30012
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30010
      published: 30010
      protocol: tcp
  storagenode3:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30020
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode3:30021
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30021
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30022
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30020
      published: 30020
      protocol: tcp
  storagenode4:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30030
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode4:30031
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30031
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30032
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30030
      published: 30030
      protocol: tcp
  storagenode5:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30040
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode5:30041
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30041
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30042
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30040
      published: 30040
      protocol: tcp
  storagenode6:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30050
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode6:30051
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30051
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30052
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30050
      published: 30050
      protocol: tcp
  storagenode7:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30060
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode7:30061
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30061
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30062
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30060
      published: 30060
      protocol: tcp
  storagenode8:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30070
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode8:30071
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30071
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30072
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30070
      published: 30070
      protocol: tcp
  storagenode9:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30080
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode9:30081
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30081
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30082
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: img.dev.storj.io/storjup/storj:1.83.2
    ports:
    - mode: ingress
      target: 30080
      published: 30080
      protocol: tcp
networks: {}
