// Ignore style warnings for for uplink-c bindings
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include uplink-c bindings (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
