name: uplink-sys

on:
  push:
    branches: ["main"]
    paths:
      - 'uplink-sys/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'docker-compose.yaml'
      - 'Makefile'
  pull_request:
    paths:
      - 'uplink-sys/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'docker-compose.yaml'
      - 'Makefile'

env:
  # Show colors for cargo output
  CARGO_TERM_COLOR: always

jobs:
  check-implementation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: uplink-sys
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Lint
      run: make lint
    - name: Build
      run: make build
    - name: Check lib binaries for docs.rs
      run: | # The way how to check if the libs are have to date with only comparing libuplink.pc isn't ideal but it's what we have found that works.
        make update-libs-docs-rs
        test -z $(git ls-files -d -m -o .docs-rs/libuplink.pc) || (printf "the uplink-c library binaries for docs.rs aren't up to date. Update them with `make update-libs-docs-rs`\n" && exit 1)
        git clean -fd && git checkout .
    - name: Test
      run: make test
    - name: Publish crate simulation
      run: make publish-test
